# Generated by Django 3.2 on 2021-04-11 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudySpaceApi', '0014_auto_20210410_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StudySpaceApi.user'),
            preserve_default=False,
        ),
    ]
